# Generated by Django 5.1.6 on 2025-03-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='paymentticket',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='paymentticket',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='paymentticket',
            old_name='user_id',
            new_name='user',
        ),
    ]
