# Generated by Django 5.1.6 on 2025-05-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='momo_order_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AppEvent.tickettype'),
        ),
    ]
