# Generated by Django 5.1.6 on 2025-04-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
