# Generated by Django 5.1.6 on 2025-05-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0002_user_organization_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='event',
            new_name='su_kien',
        ),
    ]
