# Generated by Django 5.1.6 on 2025-05-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0002_alter_payment_momo_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentticket',
            name='qr_code',
            field=models.TextField(),
        ),
    ]
