# Generated by Django 5.1.6 on 2025-04-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
