# Generated by Django 5.1.6 on 2025-05-25 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0003_alter_paymentticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentticket',
            name='qr_code',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
