# Generated by Django 5.1.6 on 2025-04-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0003_payment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
