# Generated by Django 5.1.6 on 2025-05-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0003_rename_event_tickettype_su_kien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='su_kien',
            new_name='event',
        ),
    ]
