# Generated by Django 5.1.6 on 2025-05-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0004_alter_paymentticket_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date_time',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='event',
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='AppEvent.event')),
            ],
            options={
                'ordering': ['event_date'],
                'unique_together': {('event', 'event_date')},
            },
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_types', to='AppEvent.eventdate'),
        ),
    ]
