# Generated by Django 5.1.6 on 2025-05-27 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEvent', '0005_remove_event_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='event_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_types', to='AppEvent.eventdate'),
        ),
    ]
