# Generated by Django 5.1.6 on 2025-06-03 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppEvent", "0007_discountcode_paymentticket_discount_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Phần trăm giảm giá (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
